[workspace]
resolver = "2"
members = ["crates/zeromem", "crates/zeromem-py"]
default-members = ["crates/zeromem"]

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT"
authors = ["Panat Taranat <panat@taranat.com>"]
repository = "https://github.com/ptaranat/zeromem"

[profile.release]
lto = "thin"
